// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ExcelFinancialFunctions")>]
[<assembly: AssemblyProductAttribute("ExcelFinancialFunctions")>]
[<assembly: AssemblyDescriptionAttribute("A .NET library that provides the full set of financial functions from Excel.")>]
[<assembly: AssemblyVersionAttribute("2.4")>]
[<assembly: AssemblyFileVersionAttribute("2.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ExcelFinancialFunctions"
    let [<Literal>] AssemblyProduct = "ExcelFinancialFunctions"
    let [<Literal>] AssemblyDescription = "A .NET library that provides the full set of financial functions from Excel."
    let [<Literal>] AssemblyVersion = "2.4"
    let [<Literal>] AssemblyFileVersion = "2.4"
