name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGETS: "src\\ExcelFinancialFunctions;tests\\ExcelFinancialFunctions_Tests"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -target:$TARGETS
    - name: Build
      run: dotnet build -target:$TARGETS --no-restore
    - name: Run Tests
      run: dotnet test .\\tests\\ExcelFinancialFunctions.Tests\\ExcelFinancialFunctions.Tests.fsproj --no-build --verbosity normal
      