name: Build+Test+Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGETS: "src\\ExcelFinancialFunctions;tests\\ExcelFinancialFunctions_Tests"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore -target:$TARGETS
    - name: Build Debug
      run: dotnet build -target:$TARGETS --no-restore
    - name: Run Debug Tests (Release tests fail to discover)
      run: dotnet test .\\tests\\ExcelFinancialFunctions.Tests\\ExcelFinancialFunctions.Tests.fsproj --no-build --verbosity normal
    - name: Build Release
      run: dotnet build -target:$TARGETS --no-restore --configuration=Release
    - name: Restore tools
      run: dotnet tool restore
    - name: Run fsdocs
      run: dotnet fsdocs build --eval --strict --properties Configuration=Release
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
      